### ISSUE TITLE
permloads crashes with dimension error

### ISSUE THREAD

**Issue by micahgallen** [andersonwinkler/PermCCA#6]
Hi Anderson,

I've been playing around with the permloads and permcca for analysis of behavioral and mental health factors. I ran into a bug. 

X, Y, and Z are all 418 rows long, and running this:

> [pfwer,r,A,B,U,V] = permcca(Y,X, np, Z);

Works. 

but running the same with:

>[pfwer,r,A,B,U,V,pA,pB]` = permloads(Y,X,np,Z,[],[],[],false,2);

Gives the following error:

Permutation 1/1000: 1 Unable to perform assignment because the size of
the left side is 418-by-1 and the size of the
right side is 415-by-1.

Error in permloads (line 175)
        Vperm(:,k) = V(idxY,k:end)*Bperm(:,1);

Error in CCA_Analysis (line 35)
[pfwer,r,A,B,U,V,pA,pB] =
permloads(Y,X,np,Z,[],[],[],false,2);

I looked into the function to try and see the error but it was not obvious to me. 

Thanks,
Micah

**Comment by micahgallen** [comment]
OH - also, if I run without any input on the second to last argin, I get this error. I could only get permloads to work by setting it to false. 

> Permutation 1/1000: Index in position 2 exceeds array bounds.

Error in permloads (line 162)
        idxY = Pset(:,p);

Error in CCA_Analysis (line 35)
[pfwer,r,A,B,U,V,pA,pB] =
permloads(Y,X,np,Z,[],[],[],[],2);

**Comment by andersonwinkler** [comment]
Hi Micah,

Thank you. It seems there was a bug there indeed. Should be fixed now. Please, if you have a chance, give it another try.

Thanks!

Anderson
